/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceRouteImport } from './routes/_app.workspace'
import { Route as AppTutorRouteImport } from './routes/_app.tutor'
import { Route as AppStudyRoomsRouteImport } from './routes/_app.study-rooms'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppGeneratorRouteImport } from './routes/_app.generator'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppQuizzesIndexRouteImport } from './routes/_app.quizzes.index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app.courses.index'
import { Route as AppQuizzesIdRouteImport } from './routes/_app.quizzes.$id'
import { Route as AppCoursesSlugRouteImport } from './routes/_app.courses.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyRoomsRoute = AppStudyRoomsRouteImport.update({
  id: '/study-rooms',
  path: '/study-rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorRoute = AppGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIndexRoute = AppQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdRoute = AppQuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesSlugRoute = AppCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/generator': typeof AppGeneratorRoute
  '/notifications': typeof AppNotificationsRoute
  '/planner': typeof AppPlannerRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/settings': typeof AppSettingsRoute
  '/study-rooms': typeof AppStudyRoomsRoute
  '/tutor': typeof AppTutorRoute
  '/workspace': typeof AppWorkspaceRoute
  '/courses/$slug': typeof AppCoursesSlugRoute
  '/quizzes/$id': typeof AppQuizzesIdRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/quizzes/': typeof AppQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/generator': typeof AppGeneratorRoute
  '/notifications': typeof AppNotificationsRoute
  '/planner': typeof AppPlannerRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/settings': typeof AppSettingsRoute
  '/study-rooms': typeof AppStudyRoomsRoute
  '/tutor': typeof AppTutorRoute
  '/workspace': typeof AppWorkspaceRoute
  '/courses/$slug': typeof AppCoursesSlugRoute
  '/quizzes/$id': typeof AppQuizzesIdRoute
  '/courses': typeof AppCoursesIndexRoute
  '/quizzes': typeof AppQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/generator': typeof AppGeneratorRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/study-rooms': typeof AppStudyRoomsRoute
  '/_app/tutor': typeof AppTutorRoute
  '/_app/workspace': typeof AppWorkspaceRoute
  '/_app/courses/$slug': typeof AppCoursesSlugRoute
  '/_app/quizzes/$id': typeof AppQuizzesIdRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/quizzes/': typeof AppQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/dashboard'
    | '/generator'
    | '/notifications'
    | '/planner'
    | '/recommendations'
    | '/settings'
    | '/study-rooms'
    | '/tutor'
    | '/workspace'
    | '/courses/$slug'
    | '/quizzes/$id'
    | '/courses/'
    | '/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/dashboard'
    | '/generator'
    | '/notifications'
    | '/planner'
    | '/recommendations'
    | '/settings'
    | '/study-rooms'
    | '/tutor'
    | '/workspace'
    | '/courses/$slug'
    | '/quizzes/$id'
    | '/courses'
    | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/generator'
    | '/_app/notifications'
    | '/_app/planner'
    | '/_app/recommendations'
    | '/_app/settings'
    | '/_app/study-rooms'
    | '/_app/tutor'
    | '/_app/workspace'
    | '/_app/courses/$slug'
    | '/_app/quizzes/$id'
    | '/_app/courses/'
    | '/_app/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/study-rooms': {
      id: '/_app/study-rooms'
      path: '/study-rooms'
      fullPath: '/study-rooms'
      preLoaderRoute: typeof AppStudyRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generator': {
      id: '/_app/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AppGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes/': {
      id: '/_app/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof AppQuizzesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes/$id': {
      id: '/_app/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof AppQuizzesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$slug': {
      id: '/_app/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AppCoursesSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGeneratorRoute: typeof AppGeneratorRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudyRoomsRoute: typeof AppStudyRoomsRoute
  AppTutorRoute: typeof AppTutorRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppCoursesSlugRoute: typeof AppCoursesSlugRoute
  AppQuizzesIdRoute: typeof AppQuizzesIdRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppQuizzesIndexRoute: typeof AppQuizzesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGeneratorRoute: AppGeneratorRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudyRoomsRoute: AppStudyRoomsRoute,
  AppTutorRoute: AppTutorRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppCoursesSlugRoute: AppCoursesSlugRoute,
  AppQuizzesIdRoute: AppQuizzesIdRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppQuizzesIndexRoute: AppQuizzesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
